apiVersion: v2
description: A Helm chart for sending k8s logs to Logic Monitor
name: lm-logs
version: 0.9.0-rt01
maintainers:
  - email: dev@logicmonitor.com
    name: LogicMonitor
icon: https://logicmonitor.github.io/helm-charts-qa/lm_logo.png
appVersion: 1.4.0
home: https://logicmonitor.github.io/helm-charts-qa
